spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  security:
    user:
      name: fnb
      password: fnb
server:
  port: 8081

